// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsvscnlybsmkkgzgnjdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzdnNjbmx5YnNta2tnemdua" +
  "mRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDUwNTksImV4cCI6MjA3NDM4MTA1OX0.7sOn7aw3enZOeGbKMIPtpdg0YuEhlNQKCcrnCaFuRtM";

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase";

const storage = typeof window === "undefined" ? undefined : window.localStorage;

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
